poetry/urls.py
from django.urls import path
from . import views


app_name = 'poetry'
urlpatterns = [
              path('',views.all_poetry, name='all_poetry'),
              path('<int:test_id>/',views.detailp, name='detailp' ),
]

songs/urls.py
from django.urls import path
from . import views

app_name = 'songs'

urlpatterns = [
     path('', views.sangeet, name='sangeet'),
     path('create/',views.createmysongs,name='createmysongs'),
]

testimonials/urls.py
from django.urls import path
from . import views


app_name = 'testimonials'
urlpatterns = [
              path('',views.all_testimonials, name='all_testimonials'),
              path('<int:test_id>/',views.detail, name='detail' ),
]

wohlamhe/urls.py
from django.contrib import admin
from django.urls import path,include
from songs import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),

    #APPS
    path('testimonials/',include('testimonials.urls')),
    path('songs/',include('songs.urls')),
    path('poetry/',include('poetry.urls')),

    #AUTH
    path('signup/',views.signupuser, name ='signupuser'),
    path('logout/',views.logoutuser, name='logoutuser'),
    path('login/',views.loginuser, name='loginuser'),
    path('create/',views.createmysongs, name ='createmysongs'),

     #USERACCOUNT

     path('mymusic/',views.mymusic,name='mymusic'),




]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

poetry/models.py
from django.db import models

class Poetry(models.Model):
    Title = models.CharField(max_length=100)
    description = models.TextField()
    author = models.CharField(max_length = 100)

    def __str__(self):
        return self.Title

songs/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
   Title = models.CharField(max_length=100)
   description =models.CharField(max_length=250)
   image = models.ImageField()
   url = models.URLField()


   def __str__(self):
         return self.Title



class MySongs(models.Model):
    PlaylistName = models.CharField(max_length = 100)
    Link = models.URLField()
    created = models.DateTimeField(auto_now_add = True)
    DateCompleted = models.DateTimeField(null = True, blank= True)
    Favourite = models.BooleanField(default = False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.PlaylistName 

testimonials/models.py
from django.db import models

class Testimonials(models.Model):
    Name  = models.CharField(max_length = 20)
    Message = models.CharField(max_length = 200)

songs/forms.py
from django.forms import ModelForm
from .models import MySongs


class  CreateForm(ModelForm):
    class Meta:
        model = MySongs
        fields = ['PlaylistName','Link','Favourite']

poetry/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Poetry

def all_poetry(request):

    poetrys = Poetry.objects.all()
    return render(request,'poetry/all_poetry.html',{'poetrys':poetrys})

def detailp(request):

    return render(request,'poetry/detailp.html')

songs/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Project,MySongs
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout , authenticate
from .forms import CreateForm

def home(request):
    projects = Project.objects.all()
    return render(request,'songs/home.html',{'projects':projects})



def sangeet(request):
    return render(request,'songs/sangeet.html')

def mymusic(request):
    music = MySongs.objects.filter(user=request.user)
    return render(request,'songs/mymusic.html',{'music':music})

def signupuser(request):
    if request.method == 'GET':
        return render(request,'songs/signupuser.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('mymusic')

            except IntegrityError:
                return render(request,'songs/signupuser.html',{'form':UserCreationForm(),'error':'Please Choose a different Username.This one is already taken'})
        else :
            return render(request,'songs/signupuser.html',{'form':UserCreationForm(),'error':'Password did not match'})

def loginuser(request):
    if request.method == 'GET':
        return render(request,'songs/loginuser.html',{'form':AuthenticationForm()})
    else :
        user = authenticate(request,username = request.POST['username'],password = request.POST['password'])
        if user is None:
            return render(request,'songs/loginuser.html',{'form':AuthenticationForm(),'error':'username and password doesnot match.'})
        else:
            login(request, user)
            return redirect('mymusic')

def createmysongs(request):
    if request.method == 'GET':
        return render(request,'songs/createmysongs.html',{'form':CreateForm()})
    else:
        try:
            form = CreateForm(request.POST)
            newmysong = form.save(commit=False)
            newmysong.user = request.user
            newmysong.save()
            return redirect('mymusic')
        except ValueError:
            return render(request,'songs/createmysongs.html',{'form':CreateForm(),'error':'Bad Data passed in. Try Again'})

def logoutuser(request):
       if request.method == 'POST':
           logout(request)
           return redirect('home')

testimonials/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Testimonials

def all_testimonials(request):
    test = Testimonials.objects.all()

    return render (request,'testimonials/all_testimonials.html',{'test':test})


def detail(request,test_id):
    test = get_object_or_404(Testimonials,pk=test_id)
    return render (request,'testimonials/detail.html',{'test':test})

poetry/templates/poetry/all_poetry.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;1,300&family=Metal+Mania&display=swap" rel="stylesheet">
    <title>SurSargam</title>
  </head>
  <body>
    <section class ="container-fluid py-1">
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Welcome</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Saga</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'signupuser' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Music Portals
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="https://www.spotify.com/in/" target="_blank" >Spotify</a>
                  <a class="dropdown-item" href="https://www.smule.com/" target="_blank" >Smule for Singing</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="https://www.youtube.com" target= "_blank" >Youtube</a>

                </div>
              </li>
            </ul>

          </div>
          </nav>
</section>
{% load static %}

<section class ="container" py-3>
  <div class="row container-fluid ">
    <img class="img-fluid" src = "{% static 'poetry/1.jpg' %}">
  </div>
</section>
<section class ="container" id ="poetry">
      <div class="row container-fluid ">
    <a href="https://www.shayarism.com/dosti" target="_blank"><h1>Shayari</h1></a>
    <p >Shayari has unique charm and the ability to mesmerise.
     When you encounter shayari, the whole atmosphere changes and you forget all about your worldly tasks.
     It has the ability of making even the painful events as sweet by its tone and expression.
     Poetry has the power to highlight all your senses and make you see beyond the world in front of you.
     When you allow yourself to be consumed by poetry, you open a world for yourself where everything is
     possible and nothing is what it seems.
     This magical world will make you fall in love with it and you will come back for more again and again.</p>
    </div>
    <p>Please visit us soon ....This section is still in development phase.</p>
</section>
<!--<section>
      <div class ="container-fluid">
          <h2> we have {{poetrys.count}} shayari{{poetrys.count| pluralize}}</h2>
           {% for poetry in poetrys %}
             <a href="#">{{poetry.Title}}</a>
             <br>
             {{poetry.description}}
             <br>
             {{poetry.author}}
             <br>
          {% endfor %}
    </div>
</section>-->


<br>
<br>

{% block content %}{% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <footer class="text-center bg-dark text-white">
    <p> &copy;2020 SurSargam, Inc. All Rights Reserved.</p>

  </footer>


</body>
</html>

songs/templates/songs/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!--  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;1,300&family=Metal+Mania&display=swap" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <title>SurSargam</title>
    <style>
  /* Make the image fully responsive   margin: 0; padding: 0; font-family: 'Josefin Sans', sans-serif;*/
    *{


      margin: 0; padding: 0;  font-family: 'Abel', sans-serif;
    }


  .carousel-inner img {
    width: 100%;
    height: 100%;
  }
  </style>
  </head>
  <body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">SurSargam</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#home">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#saga">Saga</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'signupuser' %}">New User</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Treasures
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#poetry">Poetry</a>
            <a class="dropdown-item" href="#poetry">Songs</a>
            <div class="dropdown-divider"></div>
            <!--<a class="dropdown-item" href="#poetry">Testimonials</a>-->
          </div>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Music Portals
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="https://www.spotify.com/in/" target="_blank" >Spotify</a>
                  <a class="dropdown-item" href="https://www.smule.com/" target="_blank" >Smule for Singing</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="https://www.youtube.com" target= "_blank" >Youtube</a>
                </div>
        </li>
    </ul>
  </div>
</nav>
<!--<embed src="/html/Kalimba.mp3" loop="true" autostart="true" width="2" height="0">-->
<section class="container-fluid py-3">

<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'songs/music.jpg' %}" alt="Music" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="{% static 'songs/nature.jpg' %}" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="{% static 'songs/trees.jpg' %}" width="1100" height="500">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
</header>
</section>
<section class="container-fluid">
{% if user.is_authenticated  %}

Logged In as {{ user.username }}

<form action="{% url 'logoutuser' %}" method="POST">
{% csrf_token %}
<button type ="submit" class="btn btn-primary">Logout</button>
</form>

{% else %}
<a href="{% url 'signupuser' %}">Sign Up</a>
<a href="{% url 'loginuser' %}">Login</a>

{% endif %}
<br>
<br>
</section>


{% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <footer class="text-center bg-dark text-white">
      <p> &copy;2020 SurSargam, Inc. All Rights Reserved.</p>

    </footer>


  </body>
</html>

songs/templates/songs/base1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;1,300&family=Metal+Mania&display=swap" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <title>SurSargam</title>
    <style>
  /* Make the image fully responsive   margin: 0; padding: 0; font-family: 'Josefin Sans', sans-serif;*/
    *{


      margin: 0; padding: 0;  font-family: 'Abel', sans-serif;
    }
  </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>



      <li class="nav-item">
        <a class="nav-link" href="{% url 'mymusic' %}">mymusic</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Music Portals
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://www.spotify.com/in/" target="_blank" >Spotify</a>
          <a class="dropdown-item" href="https://www.smule.com/" target="_blank" >Smule for Singing</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="https://www.youtube.com" target= "_blank" >Youtube</a>

        </div>
      </li>
    </ul>

  </div>
  </nav>

  <section >
    <div class ="container-fluid">
          {% if user.is_authenticated  %}

          Logged In as {{ user.username }}
          <br>
          <form action="{% url 'logoutuser' %}" method="POST">
          {% csrf_token %}
          <button type ="submit">Logout</button>
          </form>

          {% else %}
          <a href="{% url 'signupuser' %}">Sign Up</a>
          <a href="{% url 'loginuser' %}">Login</a>

          {% endif %}
    </div>
</section>
  <br>
  <br>

  {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <footer class="text-center bg-dark text-white">
      <p> &copy;2020 SurSargam, Inc. All Rights Reserved.</p>

    </footer>


  </body>
  </html>

songs/templates/songs/base2.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;1,300&family=Metal+Mania&display=swap" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <title>SurSargam</title>
    <style>
  /* Make the image fully responsive   margin: 0; padding: 0; font-family: 'Josefin Sans', sans-serif;*/
    *{


      margin: 0; padding: 0;  font-family: 'Abel', sans-serif;
    }
  </style>
  </head>
  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">SurSargam</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#signup">Sign Up</a>
        </li>

        <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Music Portals
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="https://www.spotify.com/in/" target="_blank" >Spotify</a>
                  <a class="dropdown-item" href="https://www.smule.com/" target="_blank" >Smule for Singing</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="https://www.youtube.com" target= "_blank" >Youtube</a>
                </div>
          </li>
    </ul>
    </div>
  </nav>

  {% block content %}{% endblock %}
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

      <footer class="text-center bg-dark text-white">
        <p> &copy;2020 SurSargam, Inc. All Rights Reserved.</p>

      </footer>


    </body>
  </html>

songs/templates/songs/createmysongs.html
{% extends "songs/base1.html" %}

{% load static %}

{% block content %}
<section class="py-2">
  <div class="container text-center">

      <h2>{{ error }}</h2>

      <form method = "POST">
        {% csrf_token %}
      {{ form.as_p }}
      <button type ="submit">Save</button>
      </form>
  </div>
</section>

{% endblock %}

songs/templates/songs/loginuser.html
{% extends "songs/base3.html" %}
{% load static %}
{% block content %}

<section class= "container">
  <div class="row text-center ml-4 py-3">
   <img src="{% static 'songs/7.jpg' %}" class ="img-fluid" alt="music" >
  </div>
  <div class="row text-center ml-3 mb-3"id ="login">
            <h2>{{ error }}</h2>
       <br>
      <form method = "POST">
        {% csrf_token %}
      {{ form.as_p }}
      <button type ="submit" class="btn btn-info">Login</button>
      </form>
  </div>
</section>

{% endblock %}

songs/templates/songs/logoutuser.html
logged out
{%csrf_token%}

songs/templates/songs/mymusic.html
{% extends 'songs/base1.html' %}
{% load static %}
{% block content %}

<section class="container">
  <div class="row container">
    <img  class ="img-fluid" src="{% static 'songs/6.jpg' %}" alt="music" >
  </div>
  <div>
  <ul>
      {% if user.is_authenticated  %}

      <h2>Create Your Own Playlist  {{ user.username }}</h2>
      <a href="{% url 'songs:createmysongs' %}" class="btn btn-primary">Create</a>
      {% endif %}
       {% for m in music %}
       <li>
          {% if m.Favourite %}<b>{% endif %}<a href="{{m.Link}}"target = "_blank">{{ m.PlaylistName }}</a>{% if m.favourite %}</b>{% endif %}
       </li>
       {% endfor %}
       <br>

    </ul>
    </div>
</section>




{% endblock %}

testimonials/templates/testimonials/all_testimonials.html
{% extends "songs/base1.html"  %}
{% load static %}

{% block content %}

<img src = "{% static 'testimonials/t.png' %}" width= 1200>
<h1> Testimonials are merely a Tribute. Feel free to priveledge us by letting us know How you felt, we would love to publish them.</h1>

<br>
{% for t in test %}
<h3>{{ t.Name}}</h3>
{{ t.Message }}

<br>
{% endfor %}

{% endblock  %}